### ISSUE TITLE
How are you?

### ISSUE THREAD

**Issue by AndreaGriffiths11** [AndreaGriffiths11/compose24#2]
## Comment to win

Leave a comment in the comments section to participate in the raffle, thank you!

<img src="https://github.com/user-attachments/assets/7dae2f60-9fed-42ac-80dc-2ba4339180bf" alt="mona" width="400"/>

**Comment by kaelig** [comment]
First

**Comment by serhalp** [comment]
First

**Comment by sarimabbas** [comment]
🎉🚀🚀 great talk!

**Comment by abbeyperini** [comment]
🥰🎉🔥✨

**Comment by nsainaney** [comment]
Love copilot!

**Comment by DavidWells** [comment]
Good! Great talk!

**Comment by angelausy** [comment]
🦦

**Comment by brohde** [comment]
Great :)

**Comment by paulgb** [comment]
🧸😍

**Comment by rhythm-navan** [comment]
🌼

**Comment by alexeysergeev-cm** [comment]
Hello World 🌍

**Comment by AndrewKepson** [comment]
🤯

**Comment by Plopix** [comment]
plop!

**Comment by alexbit-codemod** [comment]
Hellloooo from Codemod! 🥳

**Comment by marco-salcedo** [comment]
🚀🚀🚀🚀🚀🚀 let's go!

**Comment by newtrat** [comment]
I love Mona 🥺

**Comment by serhalp** [comment]
Testing whether you accounted for duplicates 😈 (1)

**Comment by serhalp** [comment]
Testing whether you accounted for duplicates 😈 (2)

**Comment by MarkTechson** [comment]
So far so good! The session is great and I’m having a great time

**Comment by serhalp** [comment]
Testing whether you accounted for duplicates 😈 (3)

**Comment by lavanpuri17** [comment]
copilot for the win!

**Comment by whazziz** [comment]
👋

**Comment by ashhitch** [comment]
Hello from Ash @ Fresh Egg  🥚

**Comment by SmartyP** [comment]
Winner winner chicken dinner

**Comment by niklasvatn** [comment]
❤️

**Comment by bobmonsour** [comment]
Live from Compose 2024, this is my comment!

**Comment by estelle** [comment]
Last (maybe) 😝

**Comment by mattlaguardia** [comment]
Hello World!

**Comment by LuLaValva** [comment]
Hey!

**Comment by jadeallencook** [comment]
Hello world!

**Comment by AndrewKepson** [comment]
> Testing whether you accounted for duplicates 😈 (3)

I guess not 🤣 (maybe)

**Comment by rhythm-navan** [comment]
> Testing whether you accounted for duplicates 😈 (3)

The duplicates worked 😂

**Comment by AndreaGriffiths11** [comment]
Congrats @serhalp, the logic to remove dupes was supposed to go in live lol...Oh we'll! Thanks everyone for playing. Let's do one more if you are up for it...I'll pop the removal on the code and we'll draw again 🍀

**Comment by AndreaGriffiths11** [comment]
### Congratulations @newtrat 
[draw video recording](https://www.canva.com/design/DAGSjWgtTWc/DDG4D8mBS7NYjKmFv-j_UA/view?utm_content=DAGSjWgtTWc&utm_campaign=designshare&utm_medium=link&utm_source=editor)!! DM me via Twitter @alacolombiadev or through email: andreagriffiths11@github.com 

Thank you all so much for participating!
